version: "3.9" 
services:
  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=praktikum
    healthcheck:
      test: pg_isready -U postgres
      interval: 1s
      timeout: 1s
      retries: 5
      start_period: 1s
    